production:
  sessions:
    default:
      database: mongoid_shell_tests
      hosts:
        - localhost:27017
    single_host:
      # A single remote server.
      hosts:
        - something.mongohq.com:27017
      database: mongoid
      username: user
      password: password
    replica_set:
      # This configuration is a 3 node replica set.
      hosts:
        - dedicated1.myapp.com:27017
        - dedicated2.myapp.com:27017
        - dedicated3.myapp.com:27017
      database: mongoid
      username: user
      password: password
    # This configuration shows an authenticated replica set via a uri.
    url:
      uri: mongodb://user:password@59.1.22.1:27017,59.1.22.2:27017/mongoid
